<?php

/**
 * @file
 * TODO
 */


/**
 * Implements hook_commerce_currency_info_alter().
 */
function plazik_commerce_prices_commerce_currency_info_alter(&$currencies, $langcode) {
  $currencies['USD']['format_callback'] = 'plazik_commerce_prices_commerce_currency_format';
  $currencies['AUD']['format_callback'] = 'plazik_commerce_prices_commerce_currency_format';
  $currencies['GBP']['format_callback'] = 'plazik_commerce_prices_commerce_currency_format';
  $currencies['EUR']['format_callback'] = 'plazik_commerce_prices_commerce_currency_format';
}

/**
 * Currency format callback.
 *
 * Remove decimal places from output
 * while keeping commerce_amount_to_decimal formatting the same
 *
 * See: commerce_currency_format
 */
function plazik_commerce_prices_commerce_currency_format($amount, $currency, $object) {
  $round_amount = commerce_currency_round(abs($amount), $currency);
  $price = number_format($round_amount, 0, $currency['decimal_separator'], $currency['thousands_separator']);

  $replacements = array(
    '@code_before' => $currency['code_placement'] == 'before' ? $currency['code'] : '',
    '@symbol_before' => $currency['symbol_placement'] == 'before' ? $currency['symbol'] : '',
    '@price' => $price,
    '@symbol_after' => $currency['symbol_placement'] == 'after' ? $currency['symbol'] : '',
    '@code_after' => $currency['code_placement'] == 'after' ? $currency['code'] : '',
    '@negative' => $amount < 0 ? '-' : '',
    '@symbol_spacer' => $currency['symbol_spacer'],
    '@code_spacer' => $currency['code_spacer'],
  );

  return trim(t('@code_before@code_spacer@negative@symbol_before@price@symbol_spacer@symbol_after@code_spacer@code_after', $replacements));
}
